// Package tracing owns the narrow, launch-time trace correlation contract.
// It deliberately has no network code: the client continues to talk directly
// to FreeInference and normal requests are never given X-Request-ID or probe
// headers by this package.
package tracing

import (
	"crypto/rand"
	"encoding/base32"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net/textproto"
	"os"
	"path/filepath"
	"strings"
	"time"
	"unicode"
)

const (
	TraceIDPrefix       = "fic-v1-"
	TraceIDLength       = len(TraceIDPrefix) + 26
	TraceSessionEnv     = "FI_TRACE_SESSION_ID"
	TraceManagedEnv     = "FI_TRACE_MANAGED"
	TraceSourceEnv      = "FI_TRACE_SOURCE"
	TraceClientEnv      = "FI_TRACE_CLIENT"
	TraceReceiptEnv     = "FI_TRACE_RECEIPT"
	SessionHeader       = "X-Session-ID"
	maxHeaderBlockBytes = 64 << 10
	maxHeaderLineBytes  = 8 << 10
	maxReceiptBytes     = 16 << 10
)

// HeaderMapping describes the environment-backed session-header mapping Codex
// uses for direct requests to the selected provider.
type HeaderMapping struct {
	Header string
	Env    string
}

// CodexHeaderMappings returns the documented mapping installed in a selected
// Codex provider. Only the opaque per-launch session ID is mapped.
func CodexHeaderMappings() []HeaderMapping {
	return []HeaderMapping{{Header: SessionHeader, Env: TraceSessionEnv}}
}

type Source string

const (
	SourceCompanionGenerated Source = "companion_generated"
	SourceExistingHeader     Source = "existing_client_header"
	SourceNone               Source = "none"
)

// GenerateTraceID creates a 128-bit opaque, lowercase base32 identifier.
func GenerateTraceID() (string, error) {
	var raw [16]byte
	if _, err := rand.Read(raw[:]); err != nil {
		return "", fmt.Errorf("generate trace id: %w", err)
	}
	return TraceIDPrefix + strings.ToLower(base32.StdEncoding.WithPadding(base32.NoPadding).EncodeToString(raw[:])), nil
}

// ValidateTraceID accepts only IDs generated by this version of the launcher.
func ValidateTraceID(id string) bool {
	if len(id) != TraceIDLength || !strings.HasPrefix(id, TraceIDPrefix) {
		return false
	}
	for _, r := range id[len(TraceIDPrefix):] {
		if !((r >= 'a' && r <= 'z') || (r >= '2' && r <= '7')) {
			return false
		}
	}
	// A 128-bit value encodes to 26 base32 symbols. The final symbol carries
	// only three data bits; the remaining two bits must be zero. Without this
	// check, ValidateTraceID accepts strings that GenerateTraceID can never
	// produce.
	const alphabet = "abcdefghijklmnopqrstuvwxyz234567"
	if value := strings.IndexByte(alphabet, id[len(id)-1]); value < 0 || value&3 != 0 {
		return false
	}
	return true
}

func validSource(source Source) bool {
	return source == SourceCompanionGenerated || source == SourceExistingHeader || source == SourceNone
}

// ComposeClaudeCustomHeaders preserves the caller's header block byte-for-
// byte. A valid existing X-Session-ID is never replaced. Invalid blocks fail
// open to the caller, which should launch the client without Companion trace
// injection.
func ComposeClaudeCustomHeaders(existing, generatedID string) (string, string, Source, error) {
	if len(existing) > maxHeaderBlockBytes {
		return existing, "", SourceNone, errors.New("ANTHROPIC_CUSTOM_HEADERS is too large")
	}
	if generatedID != "" && !ValidateTraceID(generatedID) {
		return existing, "", SourceNone, errors.New("invalid generated trace id")
	}
	if existing == "" {
		if generatedID == "" {
			return "", "", SourceNone, nil
		}
		return SessionHeader + ": " + generatedID, generatedID, SourceCompanionGenerated, nil
	}

	lines := strings.Split(existing, "\n")
	var existingID string
	for i, line := range lines {
		if line == "" && i == len(lines)-1 {
			continue
		}
		if len(line) == 0 || len(line) > maxHeaderLineBytes || strings.ContainsAny(line, "\r\x00") {
			return existing, "", SourceNone, errors.New("malformed custom header block")
		}
		name, value, ok := strings.Cut(line, ":")
		name = strings.TrimSpace(name)
		if !ok || !validHeaderName(name) || strings.TrimSpace(value) == "" && strings.EqualFold(name, SessionHeader) {
			return existing, "", SourceNone, errors.New("malformed custom header block")
		}
		value = strings.TrimSpace(value)
		if !validHeaderValue(value) {
			return existing, "", SourceNone, errors.New("malformed custom header block")
		}
		if strings.EqualFold(textproto.CanonicalMIMEHeaderKey(name), SessionHeader) {
			if existingID != "" {
				return existing, "", SourceNone, errors.New("duplicate X-Session-ID header")
			}
			existingID = value
		}
	}
	if existingID != "" {
		if !ValidateTraceID(existingID) {
			return existing, "", SourceNone, errors.New("existing X-Session-ID is not a valid Companion trace ID")
		}
		return existing, existingID, SourceExistingHeader, nil
	}
	if generatedID == "" {
		return existing, "", SourceNone, nil
	}
	separator := "\n"
	if strings.HasSuffix(existing, "\n") {
		separator = ""
	}
	composed := existing + separator + SessionHeader + ": " + generatedID
	if len(composed) > maxHeaderBlockBytes {
		return existing, "", SourceNone, errors.New("composed custom header block is too large")
	}
	return composed, generatedID, SourceCompanionGenerated, nil
}

func validHeaderName(name string) bool {
	if name == "" {
		return false
	}
	for _, r := range name {
		if !(unicode.IsLetter(r) || unicode.IsDigit(r) || strings.ContainsRune("!#$%&'*+-.^_`|~", r)) || r > 127 {
			return false
		}
	}
	return true
}

func validHeaderValue(value string) bool {
	if len(value) > maxHeaderLineBytes || strings.ContainsAny(value, "\r\n") {
		return false
	}
	for _, r := range value {
		if r < 0x20 || r == 0x7f {
			return false
		}
	}
	return true
}

// ValidateClaudeCustomHeaders checks only syntax and header safety; it does
// not change the block or disclose values.
func ValidateClaudeCustomHeaders(existing string) error {
	_, _, _, err := ComposeClaudeCustomHeaders(existing, "")
	return err
}

type LaunchReceipt struct {
	TraceID        string    `json:"trace_id"`
	Client         string    `json:"client"`
	Provider       string    `json:"provider"`
	EndpointOrigin string    `json:"endpoint_origin"`
	StartedAt      time.Time `json:"started_at"`
	HeaderName     string    `json:"header_name"`
	Source         Source    `json:"source"`
}

func validateReceipt(r LaunchReceipt) error {
	if !ValidateTraceID(r.TraceID) || r.Client == "" || len(r.Client) > 64 ||
		r.Provider == "" || len(r.Provider) > 128 || r.EndpointOrigin == "" ||
		r.HeaderName != SessionHeader || r.StartedAt.IsZero() || !validSource(r.Source) || r.Source == SourceNone {
		return errors.New("invalid trace receipt")
	}
	for _, value := range []string{r.Client, r.Provider, r.EndpointOrigin} {
		if !validHeaderValue(value) {
			return errors.New("invalid trace receipt field")
		}
	}
	return nil
}

func receiptDir() string {
	// macOS commonly exposes its per-user temporary directory through /var,
	// which is itself a system symlink to /private/var. Resolve that trusted OS
	// temp root first so descriptor-based no-follow creation can protect the
	// Companion-owned components without rejecting the platform's normal path.
	tempDir := os.TempDir()
	if resolved, err := filepath.EvalSymlinks(tempDir); err == nil {
		tempDir = resolved
	}
	return filepath.Join(tempDir, "freeinference-companion", "traces")
}

func ensurePrivateDir(path string) error {
	return ensurePrivateDirNoFollow(path)
}

// WriteLaunchReceipt writes a short-lived, private handoff for SessionStart.
func WriteLaunchReceipt(r LaunchReceipt) (string, error) {
	if err := validateReceipt(r); err != nil {
		return "", err
	}
	dir := receiptDir()
	if err := ensurePrivateDir(dir); err != nil {
		return "", fmt.Errorf("prepare trace receipt directory: %w", err)
	}
	cleanupStaleReceipts(dir, time.Now().UTC().Add(-24*time.Hour))
	body, err := json.Marshal(r)
	if err != nil {
		return "", err
	}
	path := filepath.Join(dir, r.TraceID+".json")
	f, err := os.OpenFile(path, os.O_WRONLY|os.O_CREATE|os.O_EXCL, 0600)
	if err != nil {
		return "", fmt.Errorf("create trace receipt: %w", err)
	}
	defer f.Close()
	if _, err := f.Write(body); err != nil {
		_ = os.Remove(path)
		return "", fmt.Errorf("write trace receipt: %w", err)
	}
	if err := f.Chmod(0600); err != nil {
		_ = os.Remove(path)
		return "", err
	}
	return path, nil
}

func cleanupStaleReceipts(dir string, before time.Time) {
	entries, err := os.ReadDir(dir)
	if err != nil {
		return
	}
	for _, entry := range entries {
		if entry.IsDir() || !strings.HasSuffix(entry.Name(), ".json") {
			continue
		}
		info, err := entry.Info()
		if err == nil && info.ModTime().Before(before) {
			_ = os.Remove(filepath.Join(dir, entry.Name()))
		}
	}
}

func trustedReceiptPath(path string) bool {
	if path == "" || !filepath.IsAbs(path) {
		return false
	}
	rel, err := filepath.Rel(receiptDir(), path)
	if err != nil || rel == "." || rel == ".." || strings.HasPrefix(rel, ".."+string(filepath.Separator)) {
		return false
	}
	base := filepath.Base(path)
	return filepath.Dir(path) == receiptDir() && strings.HasSuffix(base, ".json") && ValidateTraceID(strings.TrimSuffix(base, ".json"))
}

// ConsumeLaunchReceipt validates both the path and contents before deleting
// the exact receipt. A value from FI_TRACE_RECEIPT can never authorize an
// arbitrary file deletion.
func ConsumeLaunchReceipt(path, expectedClient, expectedOrigin string) (*LaunchReceipt, error) {
	if !trustedReceiptPath(path) {
		return nil, errors.New("untrusted trace receipt path")
	}
	info, err := os.Lstat(path)
	if err != nil || !info.Mode().IsRegular() || info.Mode()&os.ModeSymlink != 0 || info.Mode().Perm()&0077 != 0 {
		return nil, errors.New("invalid trace receipt file")
	}
	f, err := openReceiptNoFollow(path)
	if err != nil {
		return nil, err
	}
	body, readErr := io.ReadAll(io.LimitReader(f, maxReceiptBytes+1))
	_ = f.Close()
	if readErr != nil || len(body) > maxReceiptBytes {
		return nil, errors.New("invalid trace receipt contents")
	}
	var receipt LaunchReceipt
	if err := json.Unmarshal(body, &receipt); err != nil || validateReceipt(receipt) != nil {
		return nil, errors.New("invalid trace receipt contents")
	}
	if receipt.TraceID != strings.TrimSuffix(filepath.Base(path), ".json") {
		return nil, errors.New("trace receipt identity does not match its filename")
	}
	if expectedClient != "" && receipt.Client != expectedClient || expectedOrigin != "" && receipt.EndpointOrigin != expectedOrigin {
		return nil, errors.New("trace receipt does not match active client")
	}
	if err := os.Remove(path); err != nil {
		return nil, fmt.Errorf("consume trace receipt: %w", err)
	}
	return &receipt, nil
}

func RemoveLaunchReceipt(path string) {
	if trustedReceiptPath(path) {
		_ = os.Remove(path)
	}
}

// EnvironmentTrace returns the validated trace metadata inherited by a hook
// or status-line process. It does not trust FI_TRACE_SESSION_ID unless the
// launcher marker is present and the ID has the strict generated shape.
type InheritedTrace struct {
	SessionID string
	Source    Source
	Client    string
}

func EnvironmentTrace() (InheritedTrace, bool) {
	if os.Getenv(TraceManagedEnv) != "1" {
		return InheritedTrace{}, false
	}
	id := os.Getenv(TraceSessionEnv)
	if !ValidateTraceID(id) {
		return InheritedTrace{}, false
	}
	source := Source(os.Getenv(TraceSourceEnv))
	if !validSource(source) || source == SourceNone {
		return InheritedTrace{}, false
	}
	client := os.Getenv(TraceClientEnv)
	if client != "claude-code" && client != "codex" {
		return InheritedTrace{}, false
	}
	return InheritedTrace{SessionID: id, Source: source, Client: client}, true
}

// ReplaceEnv returns a copy of env with only the named launch variables
// replaced. It never adds request or synthetic-probe headers.
func ReplaceEnv(env []string, values map[string]string) []string {
	result := make([]string, 0, len(env)+len(values))
	seen := make(map[string]bool, len(values))
	for _, entry := range env {
		key, _, ok := strings.Cut(entry, "=")
		if value, replace := values[key]; replace {
			if !seen[key] {
				result = append(result, key+"="+value)
				seen[key] = true
			}
			continue
		}
		if ok {
			result = append(result, entry)
		}
	}
	for key, value := range values {
		if !seen[key] {
			result = append(result, key+"="+value)
		}
	}
	return result
}
