// Package tracing owns the narrow, launch-time trace correlation contract.
// It deliberately has no network code: the client continues to talk directly
// to FreeInference and normal requests are never given X-Request-ID or probe
// headers by this package.
package tracing

import (
	"crypto/rand"
	"encoding/base32"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net/textproto"
	"os"
	"path/filepath"
	"strings"
	"time"
	"unicode"
)

const (
	TraceIDPrefix            = "fic-v1-"
	TraceIDLength            = len(TraceIDPrefix) + 26
	TraceSessionEnv          = "FI_TRACE_SESSION_ID"
	TraceManagedEnv          = "FI_TRACE_MANAGED"
	TraceSourceEnv           = "FI_TRACE_SOURCE"
	TraceClientEnv           = "FI_TRACE_CLIENT"
	TraceCompanionVersionEnv = "FI_TRACE_COMPANION_VERSION"
	TraceWorkloadEnv         = "FI_TRACE_WORKLOAD"
	TraceReceiptEnv          = "FI_TRACE_RECEIPT"
	SessionHeader            = "X-Session-ID"
	ClientHeader             = "X-FI-Client"
	CompanionVersionHeader   = "X-FI-Companion-Version"
	WorkloadHeader           = "X-FI-Workload"
	WorkloadCodingAgent      = "coding-agent"
	maxHeaderBlockBytes      = 64 << 10
	maxHeaderLineBytes       = 8 << 10
	maxReceiptBytes          = 16 << 10
)

// HeaderMapping describes the environment-backed header mapping Codex uses
// for direct requests to the selected provider.
type HeaderMapping struct {
	Header string
	Env    string
}

// CodexHeaderMappings returns the bounded, static metadata headers installed
// in a selected Codex provider. The values are all Companion-owned launch
// environment variables; no prompt, path, session, or credential data is
// mapped.
func CodexHeaderMappings() []HeaderMapping {
	return []HeaderMapping{
		{Header: SessionHeader, Env: TraceSessionEnv},
		{Header: ClientHeader, Env: TraceClientEnv},
		{Header: CompanionVersionHeader, Env: TraceCompanionVersionEnv},
		{Header: WorkloadHeader, Env: TraceWorkloadEnv},
	}
}

// CorrelationMetadata is the small static classification attached to normal
// inference requests when a client is launched through Companion.
type CorrelationMetadata struct {
	Client           string
	CompanionVersion string
	Workload         string
}

// NewCorrelationMetadata validates the only non-random values Companion may
// attach to an inference request.
func NewCorrelationMetadata(client, companionVersion string) (CorrelationMetadata, error) {
	metadata := CorrelationMetadata{
		Client:           client,
		CompanionVersion: companionVersion,
		Workload:         WorkloadCodingAgent,
	}
	if err := metadata.validate(); err != nil {
		return CorrelationMetadata{}, err
	}
	return metadata, nil
}

func (m CorrelationMetadata) validate() error {
	if m.Client != "claude-code" && m.Client != "codex" {
		return errors.New("invalid correlation client")
	}
	if !validMetadataToken(m.CompanionVersion, 64) {
		return errors.New("invalid Companion version")
	}
	if m.Workload != WorkloadCodingAgent {
		return errors.New("invalid correlation workload")
	}
	return nil
}

func validMetadataToken(value string, max int) bool {
	if value == "" || len(value) > max || !validHeaderValue(value) {
		return false
	}
	for _, r := range value {
		if !(r >= 'a' && r <= 'z') &&
			!(r >= 'A' && r <= 'Z') &&
			!(r >= '0' && r <= '9') &&
			!strings.ContainsRune(".-_+", r) {
			return false
		}
	}
	return true
}

type requestHeader struct {
	Name  string
	Value string
}

func (m CorrelationMetadata) requestHeaders() []requestHeader {
	return []requestHeader{
		{Name: ClientHeader, Value: m.Client},
		{Name: CompanionVersionHeader, Value: m.CompanionVersion},
		{Name: WorkloadHeader, Value: m.Workload},
	}
}

type Source string

const (
	SourceCompanionGenerated Source = "companion_generated"
	SourceExistingHeader     Source = "existing_client_header"
	SourceNone               Source = "none"
)

// GenerateTraceID creates a 128-bit opaque, lowercase base32 identifier.
func GenerateTraceID() (string, error) {
	var raw [16]byte
	if _, err := rand.Read(raw[:]); err != nil {
		return "", fmt.Errorf("generate trace id: %w", err)
	}
	return TraceIDPrefix + strings.ToLower(base32.StdEncoding.WithPadding(base32.NoPadding).EncodeToString(raw[:])), nil
}

// ValidateTraceID accepts only IDs generated by this version of the launcher.
func ValidateTraceID(id string) bool {
	if len(id) != TraceIDLength || !strings.HasPrefix(id, TraceIDPrefix) {
		return false
	}
	for _, r := range id[len(TraceIDPrefix):] {
		if !((r >= 'a' && r <= 'z') || (r >= '2' && r <= '7')) {
			return false
		}
	}
	return true
}

func validSource(source Source) bool {
	return source == SourceCompanionGenerated || source == SourceExistingHeader || source == SourceNone
}

// ComposeClaudeCustomHeaders preserves the caller's header block and injects
// only the per-launch session ID. It remains as a compatibility wrapper for
// callers that do not need static request classification.
func ComposeClaudeCustomHeaders(existing, generatedID string) (string, string, Source, error) {
	return ComposeClaudeCustomHeadersWithMetadata(existing, generatedID, CorrelationMetadata{})
}

// ComposeClaudeCustomHeadersWithMetadata preserves caller-owned headers,
// refuses conflicting Companion metadata, and appends only the bounded static
// classification for a verified Companion launch. A valid existing
// X-Session-ID is never replaced.
func ComposeClaudeCustomHeadersWithMetadata(existing, generatedID string, metadata CorrelationMetadata) (string, string, Source, error) {
	if len(existing) > maxHeaderBlockBytes {
		return existing, "", SourceNone, errors.New("ANTHROPIC_CUSTOM_HEADERS is too large")
	}
	if generatedID != "" && !ValidateTraceID(generatedID) {
		return existing, "", SourceNone, errors.New("invalid generated trace id")
	}
	hasMetadata := metadata != (CorrelationMetadata{})
	if hasMetadata {
		if err := metadata.validate(); err != nil {
			return existing, "", SourceNone, err
		}
	}
	if existing == "" {
		if generatedID == "" {
			return "", "", SourceNone, nil
		}
		composed := SessionHeader + ": " + generatedID
		if hasMetadata {
			composed = appendMissingMetadata(composed, metadata.requestHeaders(), nil)
		}
		return composed, generatedID, SourceCompanionGenerated, nil
	}

	lines := strings.Split(existing, "\n")
	var existingID string
	seenMetadata := make(map[string]bool)
	for i, line := range lines {
		if line == "" && i == len(lines)-1 {
			continue
		}
		if len(line) == 0 || len(line) > maxHeaderLineBytes || strings.ContainsAny(line, "\r\x00") {
			return existing, "", SourceNone, errors.New("malformed custom header block")
		}
		name, value, ok := strings.Cut(line, ":")
		name = strings.TrimSpace(name)
		if !ok || !validHeaderName(name) || strings.TrimSpace(value) == "" && strings.EqualFold(name, SessionHeader) {
			return existing, "", SourceNone, errors.New("malformed custom header block")
		}
		value = strings.TrimSpace(value)
		if !validHeaderValue(value) {
			return existing, "", SourceNone, errors.New("malformed custom header block")
		}
		if strings.EqualFold(textproto.CanonicalMIMEHeaderKey(name), SessionHeader) {
			if existingID != "" {
				return existing, "", SourceNone, errors.New("duplicate X-Session-ID header")
			}
			existingID = value
		}
		if hasMetadata {
			for _, header := range metadata.requestHeaders() {
				if !strings.EqualFold(name, header.Name) {
					continue
				}
				key := strings.ToLower(header.Name)
				if seenMetadata[key] {
					return existing, "", SourceNone, errors.New("duplicate Companion correlation header")
				}
				if value != header.Value {
					return existing, "", SourceNone, fmt.Errorf("existing %s conflicts with Companion metadata", header.Name)
				}
				seenMetadata[key] = true
				break
			}
		}
	}
	if existingID != "" {
		if !ValidateTraceID(existingID) {
			return existing, "", SourceNone, errors.New("existing X-Session-ID is not a valid Companion trace ID")
		}
		composed := existing
		if hasMetadata {
			composed = appendMissingMetadata(composed, metadata.requestHeaders(), seenMetadata)
		}
		if len(composed) > maxHeaderBlockBytes {
			return existing, "", SourceNone, errors.New("composed custom header block is too large")
		}
		return composed, existingID, SourceExistingHeader, nil
	}
	if generatedID == "" {
		return existing, "", SourceNone, nil
	}
	separator := "\n"
	if strings.HasSuffix(existing, "\n") {
		separator = ""
	}
	composed := existing + separator + SessionHeader + ": " + generatedID
	if hasMetadata {
		composed = appendMissingMetadata(composed, metadata.requestHeaders(), seenMetadata)
	}
	if len(composed) > maxHeaderBlockBytes {
		return existing, "", SourceNone, errors.New("composed custom header block is too large")
	}
	return composed, generatedID, SourceCompanionGenerated, nil
}

func appendMissingMetadata(existing string, headers []requestHeader, seen map[string]bool) string {
	if seen == nil {
		seen = make(map[string]bool)
	}
	composed := existing
	for _, header := range headers {
		key := strings.ToLower(header.Name)
		if seen[key] {
			continue
		}
		separator := "\n"
		if strings.HasSuffix(composed, "\n") {
			separator = ""
		}
		composed += separator + header.Name + ": " + header.Value
		seen[key] = true
	}
	return composed
}

func validHeaderName(name string) bool {
	if name == "" {
		return false
	}
	for _, r := range name {
		if !(unicode.IsLetter(r) || unicode.IsDigit(r) || strings.ContainsRune("!#$%&'*+-.^_`|~", r)) || r > 127 {
			return false
		}
	}
	return true
}

func validHeaderValue(value string) bool {
	if len(value) > maxHeaderLineBytes || strings.ContainsAny(value, "\r\n") {
		return false
	}
	for _, r := range value {
		if r < 0x20 || r == 0x7f {
			return false
		}
	}
	return true
}

// ValidateClaudeCustomHeaders checks only syntax and header safety; it does
// not change the block or disclose values.
func ValidateClaudeCustomHeaders(existing string) error {
	_, _, _, err := ComposeClaudeCustomHeaders(existing, "")
	return err
}

type LaunchReceipt struct {
	TraceID        string    `json:"trace_id"`
	Client         string    `json:"client"`
	Provider       string    `json:"provider"`
	EndpointOrigin string    `json:"endpoint_origin"`
	StartedAt      time.Time `json:"started_at"`
	HeaderName     string    `json:"header_name"`
	Source         Source    `json:"source"`
}

func validateReceipt(r LaunchReceipt) error {
	if !ValidateTraceID(r.TraceID) || r.Client == "" || len(r.Client) > 64 ||
		r.Provider == "" || len(r.Provider) > 128 || r.EndpointOrigin == "" ||
		r.HeaderName != SessionHeader || r.StartedAt.IsZero() || !validSource(r.Source) || r.Source == SourceNone {
		return errors.New("invalid trace receipt")
	}
	for _, value := range []string{r.Client, r.Provider, r.EndpointOrigin} {
		if !validHeaderValue(value) {
			return errors.New("invalid trace receipt field")
		}
	}
	return nil
}

func receiptDir() string {
	return filepath.Join(os.TempDir(), "freeinference-companion", "traces")
}

func ensurePrivateDir(path string) error {
	if err := os.MkdirAll(path, 0700); err != nil {
		return err
	}
	info, err := os.Lstat(path)
	if err != nil || !info.IsDir() || info.Mode()&os.ModeSymlink != 0 {
		return errors.New("trace receipt directory is not a private directory")
	}
	return os.Chmod(path, 0700)
}

// WriteLaunchReceipt writes a short-lived, private handoff for SessionStart.
func WriteLaunchReceipt(r LaunchReceipt) (string, error) {
	if err := validateReceipt(r); err != nil {
		return "", err
	}
	dir := receiptDir()
	if err := ensurePrivateDir(dir); err != nil {
		return "", fmt.Errorf("prepare trace receipt directory: %w", err)
	}
	cleanupStaleReceipts(dir, time.Now().UTC().Add(-24*time.Hour))
	body, err := json.Marshal(r)
	if err != nil {
		return "", err
	}
	path := filepath.Join(dir, r.TraceID+".json")
	f, err := os.OpenFile(path, os.O_WRONLY|os.O_CREATE|os.O_EXCL, 0600)
	if err != nil {
		return "", fmt.Errorf("create trace receipt: %w", err)
	}
	defer f.Close()
	if _, err := f.Write(body); err != nil {
		_ = os.Remove(path)
		return "", fmt.Errorf("write trace receipt: %w", err)
	}
	if err := f.Chmod(0600); err != nil {
		_ = os.Remove(path)
		return "", err
	}
	return path, nil
}

func cleanupStaleReceipts(dir string, before time.Time) {
	entries, err := os.ReadDir(dir)
	if err != nil {
		return
	}
	for _, entry := range entries {
		if entry.IsDir() || !strings.HasSuffix(entry.Name(), ".json") {
			continue
		}
		info, err := entry.Info()
		if err == nil && info.ModTime().Before(before) {
			_ = os.Remove(filepath.Join(dir, entry.Name()))
		}
	}
}

func trustedReceiptPath(path string) bool {
	if path == "" || !filepath.IsAbs(path) {
		return false
	}
	rel, err := filepath.Rel(receiptDir(), path)
	if err != nil || rel == "." || rel == ".." || strings.HasPrefix(rel, ".."+string(filepath.Separator)) {
		return false
	}
	base := filepath.Base(path)
	return filepath.Dir(path) == receiptDir() && strings.HasSuffix(base, ".json") && ValidateTraceID(strings.TrimSuffix(base, ".json"))
}

// ConsumeLaunchReceipt validates both the path and contents before deleting
// the exact receipt. A value from FI_TRACE_RECEIPT can never authorize an
// arbitrary file deletion.
func ConsumeLaunchReceipt(path, expectedClient, expectedOrigin string) (*LaunchReceipt, error) {
	if !trustedReceiptPath(path) {
		return nil, errors.New("untrusted trace receipt path")
	}
	info, err := os.Lstat(path)
	if err != nil || !info.Mode().IsRegular() || info.Mode()&os.ModeSymlink != 0 || info.Mode().Perm()&0077 != 0 {
		return nil, errors.New("invalid trace receipt file")
	}
	f, err := os.Open(path)
	if err != nil {
		return nil, err
	}
	body, readErr := io.ReadAll(io.LimitReader(f, maxReceiptBytes+1))
	_ = f.Close()
	if readErr != nil || len(body) > maxReceiptBytes {
		return nil, errors.New("invalid trace receipt contents")
	}
	var receipt LaunchReceipt
	if err := json.Unmarshal(body, &receipt); err != nil || validateReceipt(receipt) != nil {
		return nil, errors.New("invalid trace receipt contents")
	}
	if expectedClient != "" && receipt.Client != expectedClient || expectedOrigin != "" && receipt.EndpointOrigin != expectedOrigin {
		return nil, errors.New("trace receipt does not match active client")
	}
	if err := os.Remove(path); err != nil {
		return nil, fmt.Errorf("consume trace receipt: %w", err)
	}
	return &receipt, nil
}

func RemoveLaunchReceipt(path string) {
	if trustedReceiptPath(path) {
		_ = os.Remove(path)
	}
}

// EnvironmentTrace returns the validated trace metadata inherited by a hook
// or status-line process. It does not trust FI_TRACE_SESSION_ID unless the
// launcher marker is present and the ID has the strict generated shape.
type InheritedTrace struct {
	SessionID string
	Source    Source
	Client    string
}

func EnvironmentTrace() (InheritedTrace, bool) {
	if os.Getenv(TraceManagedEnv) != "1" {
		return InheritedTrace{}, false
	}
	id := os.Getenv(TraceSessionEnv)
	if !ValidateTraceID(id) {
		return InheritedTrace{}, false
	}
	source := Source(os.Getenv(TraceSourceEnv))
	if !validSource(source) || source == SourceNone {
		return InheritedTrace{}, false
	}
	client := os.Getenv(TraceClientEnv)
	if client != "claude-code" && client != "codex" {
		return InheritedTrace{}, false
	}
	return InheritedTrace{SessionID: id, Source: source, Client: client}, true
}

// ReplaceEnv returns a copy of env with only the named launch variables
// replaced. It never adds request or synthetic-probe headers.
func ReplaceEnv(env []string, values map[string]string) []string {
	result := make([]string, 0, len(env)+len(values))
	seen := make(map[string]bool, len(values))
	for _, entry := range env {
		key, _, ok := strings.Cut(entry, "=")
		if value, replace := values[key]; replace {
			if !seen[key] {
				result = append(result, key+"="+value)
				seen[key] = true
			}
			continue
		}
		if ok {
			result = append(result, entry)
		}
	}
	for key, value := range values {
		if !seen[key] {
			result = append(result, key+"="+value)
		}
	}
	return result
}
